### ISSUE TITLE
Crash in some android 4.2.2 devices

### ISSUE THREAD

**Issue by ylecollen** [vector-im/vector-android#124]
It seems that some manufacturers use a customized ROM from which MenuBuilder is not defined.
For example, Wiko Rainbow

Caused by: java.lang.NoClassDefFoundError: android.support.v7.internal.view.menu.MenuBuilder
                                                                     at android.support.design.widget.NavigationView.<init>(NavigationView.java:95)
                                                                     at android.support.design.widget.NavigationView.<init>(NavigationView.java:88)
                                                                     at java.lang.reflect.Constructor.constructNative(Native Method) 
                                                                     at java.lang.reflect.Constructor.newInstance(Constructor.java:417) 
                                                                     at android.view.LayoutInflater.createView(LayoutInflater.java:587) 
                                                                     at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:687) 
                                                                     at android.view.LayoutInflater.rInflate(LayoutInflater.java:746) 
                                                                     at android.view.LayoutInflater.inflate(LayoutInflater.java:489) 
                                                                     at android.view.LayoutInflater.inflate(LayoutInflater.java:396) 
                                                                     at android.view.LayoutInflater.inflate(LayoutInflater.java:352)

**Comment by ylecollen** [comment]
See this fix

It seems that this issue is triggers on Wiko 4.2.2 and on some Android devices.

http://blog.rolandl.fr/2015-02-08-android-wiko-samsung-et-appcompat-v7-v21.html
