### ISSUE TITLE
The call seems crashing on some devices (galaxy Note 3)

### ISSUE THREAD

**Issue by ylecollen** [vector-im/vector-android#155]
Vector Build : 10 Vector Version : 0.2.0 (9fcd4e6-2016-05-09 13:49:59 +0200) SDK Version : 0.5.4 (bffb98a-2016-05-09 12:38:11 +0200) Phone : SM-N9005 (N9005ZSUGOL1 5.0 REL) Thread: main, Activity:im.vector.activity.CallViewActivity, Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.opengl.GLSurfaceView.invalidate()' on a null object reference at org.matrix.androidsdk.call.MXJingleCall$4$1$1.run(MXJingleCall.java:404) at android.os.Handler.handleCallback(Handler.java:739) at android.os.Handler.dispatchMessage(Handler.java:95) at android.os.Looper.loop(Looper.java:145) at android.app.ActivityThread.main(ActivityThread.java:5938) at java.lang.reflect.Method.invoke(Native Method) at java.lang.reflect.Method.invoke(Method.java:372) at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1400) at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1195)

**Comment by ylecollen** [comment]
fixed with https://github.com/matrix-org/matrix-android-sdk/commit/931e5fbfe0e9d2b20894b5b947daa764de6932f3
